with open('lib/features/chat/pantallas/chats_pantalla.dart', 'r') as f:
    lines = f.readlines()

# Replace lines 121-173 (0-indexed: 120-172) with the new implementation
# Line 121 is "            return RefreshIndicator("
# Line 173 is "    );" (the end of the build method)

new_lines = lines[:120] + [
    "            final noLeidos = conversaciones.fold<int>(\n",
    "                0, (acc, c) => acc + c.noLeidos);\n",
    "            final totalMatches = perfiles.where((p) => p.esMatch).length;\n",
    "\n",
    "            return Scaffold(\n",
    "              appBar: AppBar(\n",
    "                backgroundColor: Colors.white,\n",
    "                foregroundColor: Colors.black87,\n",
    "                elevation: 0,\n",
    "                scrolledUnderElevation: 0,\n",
    "                title: const Text(\n",
    "                  'Chats',\n",
    "                  style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black87),\n",
    "                ),\n",
    "                actions: [\n",
    "                  if (noLeidos > 0)\n",
    "                    IconButton(\n",
    "                      icon: const Icon(Icons.done_all, color: Colors.black87, size: 24),\n",
    "                      tooltip: 'Marcar todas como leídas',\n",
    "                      onPressed: () async {\n",
    "                        await widget.repositorio.marcarTodasConversacionesLeidas(widget.miId);\n",
    "                        if (!mounted) return;\n",
    "                        NotificacionServicio.exito(context, 'Conversaciones marcadas como leídas');\n",
    "                      },\n",
    "                    ),\n",
    "                ],\n",
    "              ),\n",
    "              body: RefreshIndicator(\n",
    "                onRefresh: () => widget.repositorio.sincronizarAhora(),\n",
    "                child: ListView(\n",
    "                  controller: _scrollCtrl,\n",
    "                  physics: const AlwaysScrollableScrollPhysics(),\n",
    "                  padding: const EdgeInsets.fromLTRB(16, 8, 16, 80),\n",
    "                  children: [\n",
    "                    if (noLeidos > 0 || totalMatches > 0)\n",
    "                      _banner(\n",
    "                        noLeidos: noLeidos,\n",
    "                        totalMatches: totalMatches,\n",
    "                        onAction: () {\n",
    "                          if (noLeidos > 0) {\n",
    "                            final conv = conversaciones.firstWhere(\n",
    "                              (c) => c.noLeidos > 0,\n",
    "                              orElse: () => conversaciones.first,\n",
    "                            );\n",
    "                            _abrirChat(conv);\n",
    "                          } else if (perfiles.isNotEmpty) {\n",
    "                            final match = perfiles.firstWhere(\n",
    "                              (p) => p.esMatch,\n",
    "                              orElse: () => perfiles.first,\n",
    "                            );\n",
    "                            _abrirChat(_resumenDePerfil(match));\n",
    "                          }\n",
    "                        },\n",
    "                      ),\n",
    "                    const SizedBox(height: 4),\n",
    "                    if (perfiles.isNotEmpty) ...[\n",
    "                      _encabezadoSeccion('Personas'),\n",
    "                      const SizedBox(height: 4),\n",
    "                      _filaPerfiles(perfiles),\n",
    "                      const SizedBox(height: 14),\n",
    "                    ],\n",
    "                    if (conversaciones.isNotEmpty) ...[\n",
    "                      _encabezadoSeccion('Conversaciones'),\n",
    "                      const SizedBox(height: 8),\n",
    "                      for (final conv in conversaciones)\n",
    "                        Padding(\n",
    "                          padding: const EdgeInsets.only(bottom: 6),\n",
    "                          child: Dismissible(\n",
    "                            key: ValueKey(conv.otroUsuarioId),\n",
    "                            direction: DismissDirection.endToStart,\n",
    "                            background: Container(\n",
    "                              alignment: Alignment.centerRight,\n",
    "                              padding: const EdgeInsets.only(right: 20),\n",
    "                              decoration: BoxDecoration(\n",
    "                                color: Colors.redAccent,\n",
    "                                borderRadius: BorderRadius.circular(16),\n",
    "                              ),\n",
    "                              child: const Icon(Icons.delete_outline, color: Colors.white, size: 28),\n",
    "                            ),\n",
    "                            confirmDismiss: (direction) async {\n",
    "                              return await showDialog<bool>(\n",
    "                                context: context,\n",
    "                                builder: (ctx) => AlertDialog(\n",
    "                                  title: const Text('Borrar conversación'),\n",
    "                                  content: Text('¿Seguro que quieres borrar la conversación con ${conv.nombre}? Se eliminará también del servidor.'),\n",
    "                                  actions: [\n",
    "                                    TextButton(\n",
    "                                      onPressed: () => Navigator.pop(ctx, false),\n",
    "                                      child: const Text('Cancelar'),\n",
    "                                    ),\n",
    "                                    TextButton(\n",
    "                                      onPressed: () => Navigator.pop(ctx, true),\n",
    "                                      child: const Text('Borrar', style: TextStyle(color: Colors.redAccent)),\n",
    "                                    ),\n",
    "                                  ],\n",
    "                                ),\n",
    "                              );\n",
    "                            },\n",
    "                            onDismissed: (direction) async {\n",
    "                              await widget.repositorio.borrarConversacion(conv.otroUsuarioId, widget.miId);\n",
    "                              if (mounted) {\n",
    "                                NotificacionServicio.exito(context, 'Conversación borrada');\n",
    "                              }\n",
    "                            },\n",
    "                            child: Padding(\n",
    "                              padding: const EdgeInsets.only(bottom: 6),\n",
    "                              child: _fila(conv),\n",
    "                            ),\n",
    "                          ),\n",
    "                        ),\n",
    "                    ],\n",
    "                  ],\n",
    "                ),\n",
    "              ),\n",
    "            );\n",
    "          },\n",
    "        );\n",
    "      },\n",
    "    );\n",
    "  }\n",
]

# Replace lines 120-173 (0-indexed: 120-172)
# Line 121 is index 120, line 173 is index 172
new_content = lines[:120] + new_lines + lines[173:]

with open('lib/features/chat/pantallas/chats_pantalla.dart', 'w') as f:
    f.writelines(new_content)

print('Done!')